pogom:
  restart: always
  build: pogom
  expose:
    - 5000
  volumes:
    - /usr/src/app/static

nginx:
  restart: always
  build: nginx
  ports:
    - 80:80
  volumes_from:
    - pogom
  links:
    - pogom:pogom
